config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   # rootはRoom一覧画面にしておく
   root 'rooms#index'

   # resourcesを使うとRESTfulなURLを自動生成できる
   resources :rooms, only: %i[new show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room, optional: true
  validates :content, presence: true

  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all.order(:id)
  end

  def new
    Room.create!
    redirect_to root_path
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.order(:created_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="kaiwa">
    <% if message.user == current_user %>
      <% position = 'right' %>
    <% else %>
      <% position = 'left' %>
    <% end %>
    <figure class="kaiwa-img-<%= position %>">
      <%# <%= image_tag 'default.jpg' %>
      <figcaption class="kaiwa-img-description">
        <%#= message.user.email %>
      </figcaption>
    </figure>
    <div class="kaiwa-text-<%= position %>">
      <%= simple_format(message.content) %>
    </div>
  </div>
</div>

app/views/messages/_message_left.html.erb
<div class="message">
  <div class="kaiwa">
    <figure class="kaiwa-img-left">
      <%# <%= image_tag 'default.jpg' %>
      <figcaption class="kaiwa-img-description">
        <%# <%= message.user.email %>
      </figcaption>
    </figure>
    <div class="kaiwa-text-left">
      <%= simple_format(message.content) %>
    </div>
  </div>
</div>

app/views/messages/_message_right.html.erb
<div class="message">
  <div class="kaiwa">
    <figure class="kaiwa-img-right">
      <%# <%= image_tag 'default.jpg' %> 
      <figcaption class="kaiwa-img-description">
        <%# <%= message.user.email %> 
      </figcaption>
    </figure>
    <div class="kaiwa-text-right">
      <%= simple_format(message.content) %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div>
  <ul>
    <% @rooms.each do |room| %>
      <li><%= link_to "ROOM#{room.id}", room_path(room) %></li>
    <% end %>
  </ul>
  <li><%= link_to 'NEW ROOM', new_room_path %></li>
</div>

app/views/rooms/show.html.erb
<h1>Chat room No.<%= @room.id %></h1>

<div id="show_user" data-show_user="<%= current_user.id %>"></div>
<div class="col-md-12">
  <div class="chat_box">
  
    <div id="messages", data-room_id="<%= @room.id %>"></div>
    <%= render @messages %>
  </div>
  <center>
    <div class="input">
      <%= text_field nil, nil, 'data-behavior': 'room_speaker', class: 'center-block', style: 'margin-bottom: 20px; width: 100%; max-width: 500px;' %>
      <br />
      <%= button_tag '送信', class: 'chat_submit' %>
    </div>
  </center>
</div>